# Generated by Django 5.2.5 on 2025-08-31 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_workoutlog_reps_workoutlog_sets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlog',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='duration_minutes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
