# Generated by Django 5.2.5 on 2025-08-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_alter_workoutlog_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutlog',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='workoutlog',
            name='sets',
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='date',
            field=models.DateField(),
        ),
    ]
