# Generated by Django 5.2.5 on 2025-08-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_remove_workoutlog_reps_remove_workoutlog_sets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='reps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='sets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='calories_burned',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='duration_minutes',
            field=models.PositiveIntegerField(),
        ),
    ]
